CREATE TABLE IF NOT EXISTS `t_order%s` (
  `id` BIGINT (20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` BIGINT (20) NOT NULL COMMENT '用户ID',
  `order_id` BIGINT (20) NOT NULL COMMENT '订单主键',
  PRIMARY KEY (`id`)
) ENGINE = INNODB DEFAULT CHARSET = utf8mb4